kind: pipeline
name: default
steps:
- name: publish
  image: plugins/docker
  settings:
    username: nologin
    password:
      from_secret: deploy_token
    registry: rg.fr-par.scw.cloud/ipcloud
    repo: rg.fr-par.scw.cloud/ipcloud/saskia-wijnstra-nl

